### ISSUE TITLE
개발 서버를 배포한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#115]
### Administrator

```
./gradlew clean build -Pvaadin.productionMode
nohup java -jar ./build/libs/apply-0.0.1-SNAPSHOT.jar &
```

### Frontend

```
cd frontend/
npm install
npm run serve &
```

> If you're using Ubuntu 18.4 make sure you add the node 10 repository

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
apt -y install nodejs make gcc g++
```

`https://github.com/npm/cli/issues/681`

**Comment by LTTTTTE** [comment]
s3 정적 웹사이트 호스팅 (현재 archive front배포방식)
https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/dev/EnableWebsiteHosting.html

**Comment by woowahan-pjs** [comment]
- https://hotheadfactory.com/?p=2026
- https://levelup.gitconnected.com/deploying-vue-js-to-aws-with-https-and-a-custom-domain-name-3ae1f79fe188
- ACM, VPC

**Comment by woowahan-pjs** [comment]
AWS EC2 Ubuntu 18.04

```sh
sudo apt update
sudo apt install default-jre
sudo apt install default-jdk
sudo apt install ruby
sudo apt install awscli
cd /home/ubuntu/ 
sudo aws configure
AWS Access Key ID [None]: 
AWS Secret Access Key [None]: 
Default region name [None]: ap-northeast-2
Default output format [None]: json
wget https://aws-codedeploy-ap-northeast-2.s3.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
```

**Comment by woowahan-pjs** [comment]
- https://jojoldu.tistory.com/281
- https://twofootdog.tistory.com/category/IT/AWS

**Comment by woowahan-pjs** [comment]
CodeDeploy 로그 데이터 보기
https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/deployments-view-logs.html

**Comment by woowahan-pjs** [comment]
### 문제

Elastic Beanstalk 생성 시 오류가 발생한다.

> Creating load balancer failed Reason: Default VPC not found (Service: AmazonElasticLoadBalancing; Status Code: 409; Error Code: InvalidConfigurationRequest; Request ID: 5bd22acf-114f-4a4c-ae4d-1e0e5ec2c672; Proxy: null)

> Stack named 'awseb-e-pmbdem9uid-stack' aborted operation. Current state: 'CREATE_FAILED' Reason: The following resource(s) failed to create: [AWSEBLoadBalancer].

### 해결 방법

기본 VPC를 생성한다.
https://docs.aws.amazon.com/ko_kr/vpc/latest/userguide/default-vpc.html#create-default-vpc

**Comment by woowahan-pjs** [comment]
### 문제

Beanstalk 환경의 EC2 인스턴스에서 `/var/log/eb-activity.log`와 `/var/log/eb-commandprocessor.log`가 보이지 않는다.
[Elastic Beanstalk 환경에서 Amazon EC2 인스턴스의 로그 보기](https://docs.aws.amazon.com/ko_kr/elasticbeanstalk/latest/dg/using-features.logging.html)

**Comment by woowahan-pjs** [comment]
buildspec.yml

```yml
version: 0.2
phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew clean build -Pvaadin.productionMode -x test
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - ./build/libs/*.jar
    - ./appspec.yml
    - ./scripts/**
  discard-paths: yes
cache:
  paths:
    - /root/.gradle/caches/**/*
    - '**/node_modules/**/*'
```

appspec.yml

```yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
```

deploy.sh

```sh
#!/bin/bash
BUILD_PATH=$(ls /home/ubuntu/build/*.jar)
JAR_NAME=$(basename $BUILD_PATH)

CURRENT_PID=$(pgrep -f $JAR_NAME)

if [ -z $CURRENT_PID ]
then
  sleep 1
else
  kill -15 $CURRENT_PID
  sleep 5
fi

DEPLOY_PATH=/home/ubuntu/
cp $BUILD_PATH $DEPLOY_PATH
cd $DEPLOY_PATH

DEPLOY_JAR=$DEPLOY_PATH$JAR_NAME
nohup java -jar $DEPLOY_JAR > /dev/null 2> /dev/null < /dev/null &
```
