### ISSUE TITLE
2.0.0 개발을 배포한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#384]
- yarn: `REACT_APP_API_BASE_URL=$BACKEND_URL yarn build`
- npm: `REACT_APP_API_BASE_URL=$BACKEND_URL npm run build`

```yaml
version: 0.2
phases:
  install:
    commands:
      - npm install --prefix ./frontend
  build:
    commands:
      - REACT_APP_API_BASE_URL=$BACKEND_URL npm run build --prefix ./frontend
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
cache:
  paths:
    - '**/node_modules/**/*'
```
